trigger:
- master

resources:
- repo: self

variables:
  configuration: release
  targetFramework: netcoreapp3.1
  projectFile: url.shortener.core/url.shortener.core.csproj
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: restore
      inputs:
        command: restore
        projects: $(projectFile)
    - task: DotNetCoreCLI@2
      displayName: build
      inputs:
        command: build
        projects: $(projectFile)
    - task: DotNetCoreCLI@2
      displayName: test
      inputs:
        command: test
        projects: url.shortener.tests/url.shortener.tests.csproj
    - task: DotNetCoreCLI@2
      displayName: publish
      inputs:
        command: publish
        arguments: --configuration $(configuration) -o $(System.DefaultWorkingDirectory)/app/publish --framework=$(targetFramework)
    - task: Docker@2
      displayName: docker build and push
      inputs:
        containerRegistry: gkama-docker-cr
        repository: gkama/url-shortener
        command: buildAndPush
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: |
          latest