version: "3.7"

services:
  urlshortener:
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:80

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url