version: "3.7"

services:
  urlshortener:
    image: gkama/url-shortener
    depends_on:
      - postgres
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url