version: "3.7"

services:
  urlshortener:
    image: gkama/url-shortener
    container_name: url-shortener
    depends_on:
      - postgres
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: url

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url