version: "3.7"

services:
  urlshortener:
    image: gkama/url-shortener
    container_name: url-shortener
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: postgres
      DB_NAME: url
      DB_USER: root
      DB_PASSWORD: root

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root