CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE gkama_url (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    public_key uuid NOT NULL,
    created_at datetime NOT NULL,
    target character varying(1000) NOT NULL,
    short_url character varying(50) NULL,
    CONSTRAINT "PK_gkama_url" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_gkama_url_short_url" ON gkama_url (short_url);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200421042522_initial', '3.1.3');